# Generated by Django 2.2.6 on 2020-02-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200118_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='getintouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField(max_length=1000000)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.CharField(max_length=100000),
        ),
    ]
