# Generated by Django 2.2.6 on 2020-02-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20200212_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getintouch',
            old_name='email',
            new_name='email1',
        ),
    ]
