# Generated by Django 2.2.6 on 2020-02-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20200212_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='email1',
            field=models.CharField(max_length=100),
        ),
    ]
